// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:4.0.0.0
//      SpecFlow Generator Version:4.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BulkyBook.DataAccess.Tests.Repository
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Gherkin Product Repository Tests")]
    public partial class GherkinProductRepositoryTestsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "GherkinProductRepositoryTests.Feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerForAssembly(null, NUnit.Framework.TestContext.CurrentContext.WorkerId);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Repository", "Gherkin Product Repository Tests", "Examples:\r\n| ExpectedCount |\r\n| 6            |", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Updating a product\'s values")]
        [NUnit.Framework.TestCaseAttribute("1", "Title", "New Product Title", "New Product Title", null)]
        [NUnit.Framework.TestCaseAttribute("1", "Description", "Updated Description", "Updated Description", null)]
        [NUnit.Framework.TestCaseAttribute("1", "ISBN", "1234567890", "1234567890", null)]
        [NUnit.Framework.TestCaseAttribute("1", "Author", "John Doe", "John Doe", null)]
        [NUnit.Framework.TestCaseAttribute("1", "ListPrice", "25.99", "25.99", null)]
        [NUnit.Framework.TestCaseAttribute("1", "Price", "20.99", "20.99", null)]
        [NUnit.Framework.TestCaseAttribute("1", "Price50", "19.99", "19.99", null)]
        [NUnit.Framework.TestCaseAttribute("1", "Price100", "18.99", "18.99", null)]
        [NUnit.Framework.TestCaseAttribute("2", "Title", "Another Title", "Another Title", null)]
        [NUnit.Framework.TestCaseAttribute("2", "Description", "Another Description", "Another Description", null)]
        [NUnit.Framework.TestCaseAttribute("2", "ISBN", "0987654321", "0987654321", null)]
        [NUnit.Framework.TestCaseAttribute("2", "Author", "Jane Smith", "Jane Smith", null)]
        [NUnit.Framework.TestCaseAttribute("2", "ListPrice", "30.99", "30.99", null)]
        [NUnit.Framework.TestCaseAttribute("2", "Price", "28.99", "28.99", null)]
        [NUnit.Framework.TestCaseAttribute("2", "Price50", "27.99", "27.99", null)]
        [NUnit.Framework.TestCaseAttribute("2", "Price100", "26.99", "26.99", null)]
        [NUnit.Framework.TestCaseAttribute("3", "Title", "Third Product", "Third Product", null)]
        [NUnit.Framework.TestCaseAttribute("3", "Description", "Third Description", "Third Description", null)]
        [NUnit.Framework.TestCaseAttribute("3", "ISBN", "1122334455", "1122334455", null)]
        [NUnit.Framework.TestCaseAttribute("3", "Author", "Alice Cooper", "Alice Cooper", null)]
        [NUnit.Framework.TestCaseAttribute("3", "ListPrice", "35.99", "35.99", null)]
        [NUnit.Framework.TestCaseAttribute("3", "Price", "33.99", "33.99", null)]
        [NUnit.Framework.TestCaseAttribute("3", "Price50", "32.99", "32.99", null)]
        [NUnit.Framework.TestCaseAttribute("3", "Price100", "31.99", "31.99", null)]
        public async System.Threading.Tasks.Task UpdatingAProductsValues(string productId, string columnName, string columnValue, string columnValue2, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("ProductId", productId);
            argumentsOfScenario.Add("ColumnName", columnName);
            argumentsOfScenario.Add("ColumnValue", columnValue);
            argumentsOfScenario.Add("ColumnValue2", columnValue2);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Updating a product\'s values", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 13
 await testRunner.GivenAsync(string.Format("I have a product with ID {0}", productId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 14
 await testRunner.WhenAsync(string.Format("I update the {0} of a product with value {1}", columnName, columnValue), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 15
 await testRunner.ThenAsync(string.Format("the product with {0} should have its value updated as {1}", columnName, columnValue), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
